#!/bin/python3

import math
import os
import random
import re
import sys



if __name__ == '__main__':
    n = int(input().strip())

    arr = list(map(int, input().rstrip().split()))
    rarr = reversed(arr)
    for i in rarr:
        
        print(i, end=" ")       
